#! /bin/sh

# Set environment variables
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh &
picom -b &
xidlehook --not-when-audio --not-when-fullscreen --timer 360 "betterlockscreen -l dim" "" &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
source ~/.fehbg

bspc monitor -d o o o o o o

bspc config border_width        0
bspc config window_gap 10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a mpv state=floating follow=on
bspc rule -a Audacious state=floating follow=on
